/*macro for combine odds table with p-value for GLMM outputs*/

*run: ods output  tests3=type3data  OddsRatios=ordata first before the proc glimmix;

/*parameters:*/

*ordata: the odds output generated by proc glimmix;
*type3data: the type3 p-value output generated by proc glimmix;
*outdata: output dataset;

/*glmmodds: for models includes only categorical variables*/
/*glmmodds_conti: for models with continuous variables*/

%macro glmmodds(ordata=, type3data=, outdata=);
data _null_;
	set &type3data.;
	call symput("num",_n_);
run;
%put &num.;

proc contents data =&ordata. noprint
  out = name1;
run;
proc sort data = name1;
  by varnum;
run;
data name1;
  KEEP NAME LABEL varnum;
  set name1;
  if label = '' then label = name;
run;

proc sql noprint; 
 select name into: aa separated by ' '
 from name1
 where varnum<=&num.;
quit;

%put &aa.;

proc sql noprint; 
 select name into: bb separated by ' '
 from name1
 where varnum>&num. and varnum<=2*&num.;
quit;

%put &bb.;

data odds1;
 set &ordata.;
 ord +1;
 array a(&num.) $ &aa.;
 array b(&num.)  $ &bb.;
 do i=1 to &num.;
  if trim(left(a(i)))~="_" then 
	do;
	Level = trim(left(vvalue(a(i))))||" vs "||trim(left(vvalue(b(i))));
	Variable=trim(left(vname(a(i))));
	CI=strip(put(Lower,8.2))||"-"||strip(put(Upper,8.2));
	Est=strip(put(Estimate,8.2));
	end;
 end;
run;

proc sql;
	create table &outdata. as
	select c.*,d.label
	from
	(select a.ord, a.variable, a.level, a.Est, a.CI, b.ProbF, a.Lower, a.Upper
	from odds1 as a left join &type3data. as b
	on a.variable=b.effect) as c
	left join name1 as d
	on c.variable=d.name
	order by c.ord;
quit;

%mend glmmodds;


%macro glmmodds_conti(ordata=, type3data=, outdata=,conti_var=);
data _null_;
	set &type3data.;
	call symput("num",_n_);
run;
%put &num.;

proc contents data =&ordata. noprint
  out = name1;
run;
proc sort data = name1;
  by varnum;
run;
data name1;
  KEEP NAME LABEL varnum;
  set name1;
  if label = '' then label = name;
run;

proc sql noprint; 
 select name into: aa separated by ' '
 from name1
 where varnum<=&num.;
quit;

%put &aa.;

proc sql noprint; 
 select name into: bb separated by ' '
 from name1
 where varnum>&num. and varnum<=2*&num.;
quit;

%put &bb.;

data &ordata.;
set &ordata.;
if _n_>1 then &conti_var.=._;
if _n_>1 then _&conti_var.=._;
run;

data odds1;
 set &ordata.;
 ord +1;
 array a(&num.) $ &aa.;
 array b(&num.)  $ &bb.;
 do i=1 to &num.;
  if trim(left(a(i)))~="_" then 
	do;
	Level = trim(left(vvalue(a(i))))||" vs "||trim(left(vvalue(b(i))));
	Variable=trim(left(vname(a(i))));
	CI=strip(put(Lower,8.2))||"-"||strip(put(Upper,8.2));
	Est=strip(put(Estimate,8.2));
	end;
 end;
run;

proc sql;
	create table &outdata. as
	select c.*,d.label
	from
	(select a.ord, a.variable, a.level, a.Est, a.CI, b.ProbF, a.Lower, a.Upper
	from odds1 as a left join &type3data. as b
	on a.variable=b.effect) as c
	left join name1 as d
	on c.variable=d.name
	order by c.ord;
quit;

%mend glmmodds_conti;
